# Generated by Django 3.0.6 on 2020-05-22 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodNameForM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pda', models.DecimalField(decimal_places=3, max_digits=12)),
                ('upa', models.DecimalField(decimal_places=3, max_digits=12)),
                ('moz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_API.GoodNameForM')),
            ],
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
