# Generated by Django 3.0.6 on 2020-05-22 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_API', '0002_auto_20200522_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodnameform',
            name='moz',
        ),
    ]
