# Generated by Django 3.0.6 on 2020-05-22 19:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_API', '0005_auto_20200522_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tags',
            new_name='date',
        ),
        migrations.AddField(
            model_name='post',
            name='Book_value',
            field=models.CharField(default='10', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='EPS',
            field=models.CharField(default='7', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='PE_ratio',
            field=models.CharField(default='5', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(default='AC', max_length=200),
        ),
    ]
