# Generated by Django 3.0.6 on 2020-05-22 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_API', '0006_auto_20200522_1915'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Stock_API',
        ),
    ]
